name: OpenSimplexNoiseDart
version: 2.0.0
description: Open Simplex Noise implemented in Dart
environment:
  sdk: '>=2.0.0'
dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
